name: "Refresh Composer Packages Listing"
on:
  schedule:
    - cron: "0/30 * * * *"
  push:

jobs:
  refresh-listing:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: "Setup Git for later"
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git config user.email "wp-language-bot@keksi.io"
          git config user.name "WP-Languages bot"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Cache WordPress.org API Payloads
        uses: actions/cache@v2
        with:
          path: ./cache
          key: ${{ runner.os }}-packages-${{ hashFiles('**/config/wp-packages.json') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.4
          version: 2

      - name: Cache and Build the Repository
        uses: php-actions/composer@v6
        with:
          command: run-script cache-build

      - name: Commit files
        run: |
          git add -A
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
          else
            mv ./docs/index.html ./index.html
            rm -rf .git
            git init .
            echo "*" >> './.gitignore'
            echo "!index.html" >> './.gitignore'
            git add -f .gitignore index.html
            git config user.email "wp-language-bot@keksi.io"
            git config user.name "WP-Languages bot"
            git remote add origin "https://github.com/${{ github.repository }}.git"
            git commit -a -m "Automated build"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: actions/delete-package-versions@v1
        with:
          package-name: 'php-actions_composer_wp-languages.github.io'
